### ISSUE TITLE
ParamManager.getSecretsProvider() fails with NoSuchMethodException

### ISSUE THREAD

**Issue by roamingthings** [aws-powertools/powertools-lambda-java#1280]
**What were you trying to accomplish?**
Create a `SecretsProvider` without providing a `SecretsManagerClient`. This may also be true for `SSMProvider`.

The application using this implementation will not run.

## Expected Behavior
A `SecretsProvider` is created, initialized and handed back to the caller.

## Current Behavior
A `NoSuchMethodException` is thrown:
```
Caused by: java.lang.NoSuchMethodException: software.amazon.lambda.powertools.parameters.SecretsProvider.<init>(software.amazon.lambda.powertools.parameters.cache.CacheManager)
	at java.base/java.lang.Class.getConstructor0(Unknown Source)
	at java.base/java.lang.Class.getDeclaredConstructor(Unknown Source)
	at software.amazon.lambda.powertools.parameters.ParamManager.createProvider(ParamManager.java:169)
```

## Possible Solution
Create `SecretsManagerClient` and pass it to the `getSecretsProvider()` factory method.

## Steps to Reproduce (for bugs)
1. Create a `SecretsProvider` using its factory method without any parameters:
```
SecretsProvider secretsProvider = ParamManager.getSecretsProvider().defaultMaxAge(10, MINUTES);
```

## Environment

* **Powertools for AWS Lambda (Java) version used**: 1.16.0
* **Packaging format (Layers, Maven/Gradle)**: Gradle
* **AWS Lambda function runtime:** Java 11
* **Debugging logs**

> [How to enable debug mode](https://docs.powertools.aws.dev/lambda-java/#debug-mode)**

```text
...
Caused by: java.lang.NoSuchMethodException: software.amazon.lambda.powertools.parameters.SecretsProvider.<init>(software.amazon.lambda.powertools.parameters.cache.CacheManager)
	at java.base/java.lang.Class.getConstructor0(Unknown Source)
	at java.base/java.lang.Class.getDeclaredConstructor(Unknown Source)
	at software.amazon.lambda.powertools.parameters.ParamManager.createProvider(ParamManager.java:169)
```

**Comment by roamingthings** [comment]
Looking at `ParamManager.java:169` I can see that the implementation tries to create an instance using a Constructor that accepts only a `CacheManager`. This Constructor is present in the `BaseProvider` class but is not present in the `SecretsProvider` implementation.

**Comment by roamingthings** [comment]
Seems that c7aedc4d2a61013450bf472bb7a8285f8cf80e41 fixes this issue

**Comment by jeromevdl** [comment]
Thanks for reporting this and for the deep analysis. I will have a look at this.

**Comment by jeromevdl** [comment]
@roamingthings feel free to review https://github.com/aws-powertools/powertools-lambda-java/pull/1282 and let me know what you think
