### ISSUE TITLE
Unexpected error occurred when using powertools in lambda function

### ISSUE THREAD

**Issue by trourance** [aws-powertools/powertools-lambda-java#1497]
When I'm trying to use powertools ParamManager to get a secret provider, I get the following error.

## Environment

* **Powertools for AWS Lambda (Java) version used**: 1.17.0
* **Packaging format (Layers, Maven/Gradle)**: gradle
* **AWS Lambda function runtime:**
* **Debugging logs**

> [How to enable debug mode](https://docs.powertools.aws.dev/lambda-java/#debug-mode)**

```text
val provider = ParamManager.getSecretsProvider()

Unexpected error occurred. Please raise issue at https://github.com/aws-powertools/powertools-lambda-java/issues: java.lang.RuntimeException
java.lang.RuntimeException: Unexpected error occurred. Please raise issue at https://github.com/aws-powertools/powertools-lambda-java/issues
	at software.amazon.lambda.powertools.parameters.ParamManager.createProvider(ParamManager.java:189)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(Unknown Source)
	at software.amazon.lambda.powertools.parameters.ParamManager.getProvider(ParamManager.java:55)
	at software.amazon.lambda.powertools.parameters.ParamManager.getSecretsProvider(ParamManager.java:65)
	at com.example.k8s.platform.cdk.functions.FooBarAuthorizer.handleRequest(FooBarAuthorizer.kt:26)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at software.amazon.lambda.powertools.parameters.ParamManager.createProvider(ParamManager.java:185)
	... 8 more
Caused by: java.lang.NoSuchMethodError: 'void org.apache.logging.slf4j.Log4jLoggerFactory.<init>(org.apache.logging.slf4j.Log4jMarkerFactory)'
	at org.apache.logging.slf4j.SLF4JServiceProvider.initialize(SLF4JServiceProvider.java:54)
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:183)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:170)
	at org.slf4j.LoggerFactory.getProvider(LoggerFactory.java:455)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:441)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:390)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:416)
	at software.amazon.awssdk.utils.Logger.loggerFor(Logger.java:221)
	at software.amazon.awssdk.awscore.client.builder.AwsDefaultClientBuilder.<clinit>(AwsDefaultClientBuilder.java:84)
	at software.amazon.awssdk.services.secretsmanager.SecretsManagerClient.builder(SecretsManagerClient.java:4829)
	at software.amazon.lambda.powertools.parameters.SecretsProvider$Builder.createClient(SecretsProvider.java:161)
	at software.amazon.lambda.powertools.parameters.SecretsProvider$Builder.access$0(SecretsProvider.java:160)
	at software.amazon.lambda.powertools.parameters.SecretsProvider.<init>(SecretsProvider.java:83)
	... 13 more
```

**Comment by trourance** [comment]
As a side note, removing `org.apache.logging.log4j:log4j-slf4j-impl` from the dependencies suppress the error, but then there's a timeout in `Transforming org/apache/logging/log4j/core/lookup/JndiLookup (lambdainternal.CustomerClassLoader@76fb509a)`

**Comment by scottgerring** [comment]
Hey @trourance thanks for raising the issue!
Do you mind including:

* The code where you are creating the secrets provider
* Some info / code about your logging setup 

It looks like you are missing some part of slf4j needed to hook into log4j. We [support log4j ](https://docs.powertools.aws.dev/lambda/java/core/logging/)primarily in our current setup, so I'd guess that piece in the middle is involved.

**Comment by trourance** [comment]
@scottgerring In the lambda, we only use only one logger, the context logger, e.g. `context.logger.log(...)`.
In the rest of our code, we use only `org.apache.logging.log4j:log4j-core:2.17.2`, instantiated with LogManager, e.g. `val log = LogManager.getLogger(...)`

**Comment by trourance** [comment]
@scottgerring Using `log4j-slf4j2-impl` instead of `log4j-slf4j-impl` fixed that issue, thanks for pinpointing the mistake !

**Comment by scottgerring** [comment]
No worries @trourance glad to help 🙇
